### ISSUE TITLE
Need a sample project

### ISSUE THREAD

**Issue by aarya1906** [cashfree/epos#1]
Help us by providing a sample project.

**Comment by rajnandan1** [comment]
can you reach out to techsupport@cashfree.com

**Comment by arjun-cashfree** [comment]
Sample code section has been added to the docs.

**Comment by aarya1906** [comment]
please share the url

**Comment by arjun-cashfree** [comment]
https://github.com/cashfree/epos#sample-code

**Comment by aarya1906** [comment]
I am not able to generate Token.

**Comment by arjun-cashfree** [comment]
Please contact our Technical support (techsupport@cashfree.com) to get help regarding the integration. They'll be able to guide you.
